name: Deploy Terraform to AWS Environments
on:
  push:
    branches:
      - "main"
  # pull_request:
  #   types:
  #     - "opened"
  #     - "reopened"
  #     - "edited"
  #     - "synchronize"

run-name: Pull Request Integration tests during merges
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    name: Setup Dependencies
    steps:
      - name: Install Terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform

  development:
    runs-on: ubuntu-latest
    needs:
      - terraform-validate
    name: Deploy to Development
    environment: development
    concurrency: development
    steps:
      - name: Deploy
        run: sleep 60

  qa:
    runs-on: ubuntu-latest
    needs:
      - development
    name: Deploy to QA
    environment: qa
    concurrency: qa
    steps:
      - name: Deploy
        run: sleep 60

      # - name: Test variables
      #   run: echo ${{ vars.TEST_VARIABLE }}
      # - name: Test variables without quotes
      #   run: echo ${{ secrets.TEST_SECRETTTT }}
      # - run: printenv
