name: Pull Request Integration Test
on:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "edited"
      - "synchronize"

run-name: Pull Request Integration tests during merges
jobs:
  pull_request_test:
    runs-on: ubuntu-latest
    name: Integration Test
    environment: development
    steps:
      - name: Test environment variables
        run: |
          printenv
